### ISSUE TITLE
Hold to grab constantly pops up

### ISSUE THREAD

**Issue by auronx223** [owlboy/greatpug-public#20] opened 2019-05-08 20:37 UTC
**Describe the bug**

On Rare occasions, some instances constantly bring up the option to "Hold to Grab". This bug affects the instance and only seems to affect VR users for some reason. This prevents picking up any item, or sitting in seats, etc. and regardless of where you go in the map it constantly pops up every 5 seconds or so (also causes the controllers to buzz each time).

Desktop users can still pick up items and sit on seats whilst every other VR user in the instance has the issue. When changing instance to another pug seems to resolve the issue, although returning to the instance will still have the bug occur.

Some occasions I have heard the phone noises constantly follow me when this occurs, especially when pressing the grip button and holding my hand next to my head. 

**To Reproduce**

Unsure of what exactly causes this issue. Seems to be an issue with the instance and happens randomly.

**Expected behavior**

**Screenshots**

![VRChat_1920x1080_2019-05-08_20-19-16 995](https://user-images.githubusercontent.com/9289155/57654329-cd055380-75cb-11e9-9b37-345f6a798684.png)

**Are you in VR or Desktop mode?**

VR with Oculus Rift.

**Additional context**
I've only seen this bug occur in the Pug, so its possibly a bug with the map instead of VRChat.

**Comment by owlboy** [comment] 2019-05-08 20:53
Hello! I really appreciate the Bug Report. If this instance is still live, a VRChat output log would be very helpful.

This is an issue that has been on-going for over a year now. I'm not sure exactly what state it is getting into, nor sure how to reproduce it. It seems as though a pickup or pickups has gotten into what can only be described as a superposition. And the client does not notice this and reset it.

But I can only hypothesize that it seems to be an issue that is likely caused by one of the following factors:
• Triggers were broken by a modified client manipulating them or the hierarchy into a bad state.
• The instance itself is very old and has not survived all the master handoffs it has had to do
• There is an issue with older instances and buffered triggers getting out of control after a long period of time.
• Something specifically about the teleportTo VRChat Trigger is not stable and it very rarely gets tripped up.

I believe we both have not observed this in other worlds because their public instances do not last as long, and have pickups in them.

All of this could be wrong, and I am willing to investigate alternate theories as to the cause. Especially if someone can reproduce it. As it stands now, I am 75% confident this is an issue with the client or how triggers are allowed to behave, and not the world.

**Comment by auronx223** [comment] 2019-05-08 21:02
Looking in the VRChat log around when I took the picture shows a bunch of errors same as below:

2019.05.08 20:19:59 Error      -  Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path " - Props/Props (Pickups) - Main Bar/tumblr-voo-doo (2)/ObjectRespawner"

**Comment by owlboy** [comment] 2019-05-08 21:06
Thanks for the info! That looks like what I have seen in the past when this issue arises.

That Glass is literally attempting to teleport itself to a non-existent coordinate in space.

**Comment by All4thlulz** [comment] 2019-05-12 04:42
I came here to also report this issue and while it may not be of any further help here is a list on pastebin of all the different objects that were throwing errors throughout a few broken instances of the great pug. 

[Great Pug Hold To Grab Errors](https://pastebin.com/5ZpHe4ki) It is not a complete list because we are talking I have an output log with thousands of these errors over different instances.

**Comment by owlboy** [comment] 2019-05-17 19:28
@All4thlulz That bit of the log you have shared is good enough. Thanks!

**Comment by owlboy** [comment] 2019-05-17 19:36
I am pretty sure this is a bug on the VRChat/Unity side of things. The only way for me to fix it would be to remove all pickups from the world. - And that is not an option I am willing to consider right now.

The reason you may see it in The Pug more often than others is just due to the age of instances The Great Pug currently averages. Lots of people filter in an out leading to the instances to last a long time.

I did some googling on the error, and it leads me to this Unity issue:
https://issuetracker.unity3d.com/issues/transform-dot-position-values-becomes-to-nan-when-one-gameobject-rotates-while-colliding-the-edge-of-another-gameobject

Sadly this means engine bug. And I can already hear VRChat saying "not our problem, we have too much else to fix. Things work fine in the vast majority of cases with Pickup Objects."

I would hope they could put in something that catches when this is happening and reset the location of the object.

Should this be a malicious user setting the location to NAN, then that is also something VRChat has to take care of. Either with stronger security preventing modified clients, or again with a check that kicks the Pickup Object out of the bad state.

Other potential solutions to this issue, and things similar that VRChat could implement:
• Auto restart instances once every X period of time.
• Allow world owners to reset instances to manually manage such situations on their own as needed / if the world owner is willing to.
• Modify how interactions work with Pickups so that when they are in this state, they do not block interaction with pickups that are "healthy".

**Comment by owlboy** [comment] 2019-05-17 19:40
Here is the Canny item that applies to this bug. Please throw some upvotes at it:
https://vrchat.canny.io/bug-reports/p/rigidbodies-imploding-hold-to-grab-bug

**Comment by owlboy** [comment] 2019-08-12 18:27
Does anyone still see this issue happening in The Great Pug or other worlds? I have not run across it for a good while now (knock on wood). It may have been fixed in a collateral way from other work done on ObjectSync, etc.

**Comment by auronx223** [comment] 2019-08-12 21:06
I haven't seen it in awhile personally, hopefully it is resolved.

**Comment by owlboy** [comment] 2020-03-05 08:11
I think it's safe to say this has been resolved. It's weird how some bugs just vanish, and no one is quite sure why.

**Closed by owlboy** 2020-03-05 08:11 UTC
Labels: Suspected Unity Bug, vrchat-bug
