### ISSUE TITLE
Bar mirror culling wall decorations

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#112] opened 2023-06-26 12:41 UTC
Fix one bug, another pops up instantly.

![VRChat_2023-06-26_14-41-04 941_3840x2400](https://github.com/owlboy/greatpug-public/assets/35110496/73869151-f7fd-4e2c-b11d-db2d30f5c4fa)

**Comment by owlboy** [comment] 2023-07-08 05:24
I think these should all be fixed in the next build.

**Closed by owlboy** 2023-07-08 05:24 UTC
Labels: bug

**Comment by Wasmachineman-NL** [comment] 2023-08-02 21:57
The mirror is culling these again.

**Comment by owlboy** [comment] 2023-08-03 03:59
I can't reproduce this. Until you have more information beyond a screenshot, I can't do anything.

**Comment by owlboy** [comment] 2023-08-04 00:07
@Wasmachineman-NL There is a chance you saw regressions due to the recent VRChat update that contained Avatar Scaling having some bugs related to world loading. - They just updated again today to address it.

**Comment by owlboy** [comment] 2023-08-04 19:26
@Wasmachineman-NL I just got confirmation that you seeing the fire and mirror regressions were indeed due to a VRChat update issue. They fixed it in the most recent small patch. 

It wasn’t anything that was your fault or an issue with your settings.
