### ISSUE TITLE
The Great Pug front desk phone doesn't drop

### ISSUE THREAD

**Issue by HachijoTohya** [owlboy/greatpug-public#72] opened 2022-12-28 06:47 UTC
**Describe the Bug** 
The phone at the front desk will immediately snap back to its dock upon being dropped.

**Steps To Reproduce** 
Pick up the phone at the front desk, drop it anywhere

**Expected Behavior** 
The phone should drop to the floor

**Screenshots** 
https://user-images.githubusercontent.com/57164082/209769986-263f5826-3f93-4087-b9bb-9a9514e8ba04.mp4

**OutputLog**

[output_log_2022-12-28_00-08-24.txt](https://github.com/owlboy/greatpug-public/files/10312607/output_log_2022-12-28_00-08-24.txt)

**Are you in VR or Desktop mode?**
VR

**Additional Context** 
I don't know if this behavior is intended, but it wasn't always like this.

**Comment by owlboy** [comment] 2023-01-10 06:01
Thanks for reporting this. The incorrect snapping behavior should be fixed in the next build!

The intended behavior is for it to snap when it's close to the phone's home location. But that is broken right now. In the mean time, snap has been disabled on this phone.

**Closed by owlboy** 2023-01-10 06:01 UTC
Labels: bug
